--XS Warehouse 

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
USE WAREHOUSE OP_WAREHOUSE_XS;
USE DATABASE snowflake_sample_data;
USE SCHEMA TPCH_SF1000;


--S Warehouse 
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
USE WAREHOUSE OP_WAREHOUSE_S;
USE DATABASE snowflake_sample_data;
USE SCHEMA TPCH_SF1000;


--M Warehouse 
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
USE WAREHOUSE OP_WAREHOUSE_M;
USE DATABASE snowflake_sample_data;
USE SCHEMA TPCH_SF1000;



--L Warehouse 
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
USE WAREHOUSE OP_WAREHOUSE_L;
USE DATABASE snowflake_sample_data;
USE SCHEMA TPCH_SF1000;




